// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title PlonkVerifier
 * @notice On-chain verifier for PLONK proofs over BN254
 * @dev Implements the PLONK verification algorithm with optimized gas usage
 *
 * This contract verifies zero-knowledge proofs generated by the zkML system.
 * It uses the BN254 (alt_bn128) curve which has native precompile support
 * on Ethereum (EIP-196, EIP-197).
 *
 * Gas Costs (approximate):
 * - Pairing check: ~45,000 gas per pair
 * - Scalar multiplication: ~6,000 gas
 * - Point addition: ~150 gas
 * - Total verification: ~300,000-400,000 gas
 */

contract PlonkVerifier {
    // ============================================================
    // BN254 Curve Constants
    // ============================================================

    // Field modulus (p)
    uint256 constant FIELD_MODULUS = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    // Scalar field modulus (r)
    uint256 constant SCALAR_MODULUS = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // G1 generator
    uint256 constant G1_X = 1;
    uint256 constant G1_Y = 2;

    // G2 generator
    uint256 constant G2_X1 = 10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 constant G2_X2 = 11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 constant G2_Y1 = 8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 constant G2_Y2 = 4082367875863433681332203403145435568316851327593401208105741076214120093531;

    // ============================================================
    // Verifier Key (set during deployment)
    // ============================================================

    struct VerifierKey {
        uint256 n;              // Circuit size
        uint256 omega;          // Primitive n-th root of unity
        uint256 k1;             // Coset generator 1
        uint256 k2;             // Coset generator 2

        // Selector commitments [x, y]
        uint256[2] q_L;
        uint256[2] q_R;
        uint256[2] q_O;
        uint256[2] q_M;
        uint256[2] q_C;

        // Permutation commitments
        uint256[2] sigma_1;
        uint256[2] sigma_2;
        uint256[2] sigma_3;

        // SRS elements for pairing
        uint256[2] x2;          // [τ]₂
    }

    VerifierKey public vk;

    // ============================================================
    // Proof Structure
    // ============================================================

    struct Proof {
        // Round 1: Wire commitments
        uint256[2] a_commit;
        uint256[2] b_commit;
        uint256[2] c_commit;

        // Round 2: Permutation commitment
        uint256[2] z_commit;

        // Round 3: Quotient commitments
        uint256[2] t_lo_commit;
        uint256[2] t_mid_commit;
        uint256[2] t_hi_commit;

        // Round 4: Evaluations
        uint256 a_eval;
        uint256 b_eval;
        uint256 c_eval;
        uint256 sigma_1_eval;
        uint256 sigma_2_eval;
        uint256 z_omega_eval;

        // Round 5: Opening proofs
        uint256[2] w_zeta;
        uint256[2] w_zeta_omega;
    }

    // ============================================================
    // Events
    // ============================================================

    event ProofVerified(address indexed verifier, bool success);
    event VerifierKeySet(uint256 circuitSize);

    // ============================================================
    // Constructor
    // ============================================================

    constructor() {
        // Initialize with default verifier key
        // In production, this would be set via setVerifierKey()
        vk.n = 4;
        vk.omega = 0x30644e72e131a029048b6e193fd841045cea24f6fd736bec231204708f703636;
        vk.k1 = 2;
        vk.k2 = 3;
    }

    // ============================================================
    // Admin Functions
    // ============================================================

    /**
     * @notice Set the verifier key for a specific circuit
     * @param _vk The verifier key data
     */
    function setVerifierKey(VerifierKey calldata _vk) external {
        vk = _vk;
        emit VerifierKeySet(_vk.n);
    }

    // ============================================================
    // Verification Functions
    // ============================================================

    /**
     * @notice Verify a PLONK proof
     * @param proof The proof to verify
     * @param publicInputs The public inputs to the circuit
     * @return True if the proof is valid
     */
    function verify(
        Proof calldata proof,
        uint256[] calldata publicInputs
    ) external view returns (bool) {
        // Step 1: Validate proof elements are on curve
        require(_isOnCurve(proof.a_commit), "a_commit not on curve");
        require(_isOnCurve(proof.b_commit), "b_commit not on curve");
        require(_isOnCurve(proof.c_commit), "c_commit not on curve");
        require(_isOnCurve(proof.z_commit), "z_commit not on curve");
        require(_isOnCurve(proof.t_lo_commit), "t_lo_commit not on curve");
        require(_isOnCurve(proof.t_mid_commit), "t_mid_commit not on curve");
        require(_isOnCurve(proof.t_hi_commit), "t_hi_commit not on curve");
        require(_isOnCurve(proof.w_zeta), "w_zeta not on curve");
        require(_isOnCurve(proof.w_zeta_omega), "w_zeta_omega not on curve");

        // Step 2: Validate evaluations are in field
        require(proof.a_eval < SCALAR_MODULUS, "a_eval out of range");
        require(proof.b_eval < SCALAR_MODULUS, "b_eval out of range");
        require(proof.c_eval < SCALAR_MODULUS, "c_eval out of range");
        require(proof.sigma_1_eval < SCALAR_MODULUS, "sigma_1_eval out of range");
        require(proof.sigma_2_eval < SCALAR_MODULUS, "sigma_2_eval out of range");
        require(proof.z_omega_eval < SCALAR_MODULUS, "z_omega_eval out of range");

        // Step 3: Compute challenges via Fiat-Shamir
        (
            uint256 beta,
            uint256 gamma,
            uint256 alpha,
            uint256 zeta,
            uint256 v,
            uint256 u
        ) = _computeChallenges(proof, publicInputs);

        // Step 4: Compute vanishing polynomial evaluation
        uint256 zh_eval = _computeZhEval(zeta);

        // Step 5: Compute public input polynomial evaluation
        uint256 pi_eval = _computePiEval(publicInputs, zeta);

        // Step 6: Compute linearization polynomial commitment
        uint256[2] memory r_commit = _computeLinearization(proof, beta, gamma, alpha, zeta);

        // Step 7: Compute aggregated commitment for batch opening
        uint256[2] memory d_commit = _computeAggregatedCommitment(proof, r_commit, v);

        // Step 8: Compute aggregated evaluation
        uint256 d_eval = _computeAggregatedEvaluation(proof, pi_eval, v);

        // Step 9: Verify pairing equation
        return _verifyPairing(proof, d_commit, d_eval, zeta, u);
    }

    // ============================================================
    // Internal Helper Functions
    // ============================================================

    /**
     * @notice Check if a point is on the BN254 curve
     */
    function _isOnCurve(uint256[2] memory point) internal pure returns (bool) {
        if (point[0] == 0 && point[1] == 0) {
            return true; // Point at infinity
        }

        uint256 lhs = mulmod(point[1], point[1], FIELD_MODULUS);
        uint256 rhs = mulmod(mulmod(point[0], point[0], FIELD_MODULUS), point[0], FIELD_MODULUS);
        rhs = addmod(rhs, 3, FIELD_MODULUS);

        return lhs == rhs;
    }

    /**
     * @notice Compute Fiat-Shamir challenges
     */
    function _computeChallenges(
        Proof calldata proof,
        uint256[] calldata publicInputs
    ) internal pure returns (
        uint256 beta,
        uint256 gamma,
        uint256 alpha,
        uint256 zeta,
        uint256 v,
        uint256 u
    ) {
        // Beta and Gamma from Round 1
        bytes memory round1Data = abi.encodePacked(
            proof.a_commit[0], proof.a_commit[1],
            proof.b_commit[0], proof.b_commit[1],
            proof.c_commit[0], proof.c_commit[1]
        );

        for (uint256 i = 0; i < publicInputs.length; i++) {
            round1Data = abi.encodePacked(round1Data, publicInputs[i]);
        }

        beta = uint256(keccak256(abi.encodePacked(round1Data, "beta"))) % SCALAR_MODULUS;
        gamma = uint256(keccak256(abi.encodePacked(round1Data, "gamma"))) % SCALAR_MODULUS;

        // Alpha from Round 2
        alpha = uint256(keccak256(abi.encodePacked(
            proof.z_commit[0], proof.z_commit[1],
            beta, gamma,
            "alpha"
        ))) % SCALAR_MODULUS;

        // Zeta from Round 3
        zeta = uint256(keccak256(abi.encodePacked(
            proof.t_lo_commit[0], proof.t_lo_commit[1],
            proof.t_mid_commit[0], proof.t_mid_commit[1],
            proof.t_hi_commit[0], proof.t_hi_commit[1],
            alpha,
            "zeta"
        ))) % SCALAR_MODULUS;

        // V from Round 4
        v = uint256(keccak256(abi.encodePacked(
            proof.a_eval, proof.b_eval, proof.c_eval,
            proof.sigma_1_eval, proof.sigma_2_eval,
            proof.z_omega_eval,
            zeta,
            "v"
        ))) % SCALAR_MODULUS;

        // U from Round 5
        u = uint256(keccak256(abi.encodePacked(
            proof.w_zeta[0], proof.w_zeta[1],
            proof.w_zeta_omega[0], proof.w_zeta_omega[1],
            v,
            "u"
        ))) % SCALAR_MODULUS;
    }

    /**
     * @notice Compute vanishing polynomial evaluation: Z_H(zeta) = zeta^n - 1
     */
    function _computeZhEval(uint256 zeta) internal view returns (uint256) {
        uint256 result = _expMod(zeta, vk.n, SCALAR_MODULUS);
        return addmod(result, SCALAR_MODULUS - 1, SCALAR_MODULUS);
    }

    /**
     * @notice Compute public input polynomial evaluation
     */
    function _computePiEval(
        uint256[] calldata publicInputs,
        uint256 zeta
    ) internal view returns (uint256) {
        if (publicInputs.length == 0) {
            return 0;
        }

        // PI(X) = Σ pi_i * L_i(X)
        // where L_i(X) is the i-th Lagrange basis polynomial
        uint256 result = 0;
        uint256 omega_i = 1;

        for (uint256 i = 0; i < publicInputs.length; i++) {
            // L_i(zeta) = (zeta^n - 1) / (n * (zeta - omega^i))
            uint256 numerator = _computeZhEval(zeta);
            uint256 denominator = mulmod(
                vk.n,
                addmod(zeta, SCALAR_MODULUS - omega_i, SCALAR_MODULUS),
                SCALAR_MODULUS
            );
            uint256 li = mulmod(numerator, _modInverse(denominator), SCALAR_MODULUS);

            result = addmod(result, mulmod(publicInputs[i], li, SCALAR_MODULUS), SCALAR_MODULUS);
            omega_i = mulmod(omega_i, vk.omega, SCALAR_MODULUS);
        }

        return result;
    }

    /**
     * @notice Compute linearization polynomial commitment
     */
    function _computeLinearization(
        Proof calldata proof,
        uint256 beta,
        uint256 gamma,
        uint256 alpha,
        uint256 zeta
    ) internal view returns (uint256[2] memory) {
        // Simplified linearization for demonstration
        // Full implementation would include all constraint terms

        // r = q_M * a * b + q_L * a + q_R * b + q_O * c + q_C
        //   + alpha * (permutation terms)
        //   + alpha^2 * (boundary terms)

        // For now, return a placeholder
        return proof.a_commit;
    }

    /**
     * @notice Compute aggregated commitment for batch opening
     */
    function _computeAggregatedCommitment(
        Proof calldata proof,
        uint256[2] memory r_commit,
        uint256 v
    ) internal view returns (uint256[2] memory) {
        // D = r + v*a + v²*b + v³*c + v⁴*σ1 + v⁵*σ2

        uint256[2] memory result = r_commit;
        uint256 v_power = v;

        // Add v * a_commit
        result = _ecAdd(result, _ecMul(proof.a_commit, v_power));
        v_power = mulmod(v_power, v, SCALAR_MODULUS);

        // Add v² * b_commit
        result = _ecAdd(result, _ecMul(proof.b_commit, v_power));
        v_power = mulmod(v_power, v, SCALAR_MODULUS);

        // Add v³ * c_commit
        result = _ecAdd(result, _ecMul(proof.c_commit, v_power));
        v_power = mulmod(v_power, v, SCALAR_MODULUS);

        // Add v⁴ * sigma_1
        result = _ecAdd(result, _ecMul(vk.sigma_1, v_power));
        v_power = mulmod(v_power, v, SCALAR_MODULUS);

        // Add v⁵ * sigma_2
        result = _ecAdd(result, _ecMul(vk.sigma_2, v_power));

        return result;
    }

    /**
     * @notice Compute aggregated evaluation
     */
    function _computeAggregatedEvaluation(
        Proof calldata proof,
        uint256 pi_eval,
        uint256 v
    ) internal pure returns (uint256) {
        uint256 result = pi_eval;
        uint256 v_power = v;

        result = addmod(result, mulmod(proof.a_eval, v_power, SCALAR_MODULUS), SCALAR_MODULUS);
        v_power = mulmod(v_power, v, SCALAR_MODULUS);

        result = addmod(result, mulmod(proof.b_eval, v_power, SCALAR_MODULUS), SCALAR_MODULUS);
        v_power = mulmod(v_power, v, SCALAR_MODULUS);

        result = addmod(result, mulmod(proof.c_eval, v_power, SCALAR_MODULUS), SCALAR_MODULUS);
        v_power = mulmod(v_power, v, SCALAR_MODULUS);

        result = addmod(result, mulmod(proof.sigma_1_eval, v_power, SCALAR_MODULUS), SCALAR_MODULUS);
        v_power = mulmod(v_power, v, SCALAR_MODULUS);

        result = addmod(result, mulmod(proof.sigma_2_eval, v_power, SCALAR_MODULUS), SCALAR_MODULUS);

        return result;
    }

    /**
     * @notice Verify the pairing equation
     * @dev Uses EIP-197 precompile for bn256Pairing
     */
    function _verifyPairing(
        Proof calldata proof,
        uint256[2] memory d_commit,
        uint256 d_eval,
        uint256 zeta,
        uint256 u
    ) internal view returns (bool) {
        // Pairing check:
        // e(W_zeta + u*W_zeta_omega, [τ]₂) = e(zeta*W_zeta + u*zeta*omega*W_zeta_omega + D - d*G1, G2)

        // Compute left side of pairing: W_zeta + u * W_zeta_omega
        uint256[2] memory lhs_g1 = _ecAdd(
            proof.w_zeta,
            _ecMul(proof.w_zeta_omega, u)
        );

        // Compute right side numerator
        uint256[2] memory rhs_g1 = _ecAdd(
            _ecMul(proof.w_zeta, zeta),
            _ecMul(proof.w_zeta_omega, mulmod(u, mulmod(zeta, vk.omega, SCALAR_MODULUS), SCALAR_MODULUS))
        );
        rhs_g1 = _ecAdd(rhs_g1, d_commit);
        rhs_g1 = _ecAdd(rhs_g1, _ecNeg(_ecMul([G1_X, G1_Y], d_eval)));

        // Prepare pairing input
        // e(-lhs_g1, [τ]₂) * e(rhs_g1, G2) = 1
        uint256[12] memory input;

        // First pair: -lhs_g1, [τ]₂
        uint256[2] memory neg_lhs = _ecNeg(lhs_g1);
        input[0] = neg_lhs[0];
        input[1] = neg_lhs[1];
        input[2] = vk.x2[0];
        input[3] = vk.x2[1];
        input[4] = G2_X1;
        input[5] = G2_X2;

        // Second pair: rhs_g1, G2
        input[6] = rhs_g1[0];
        input[7] = rhs_g1[1];
        input[8] = G2_X1;
        input[9] = G2_X2;
        input[10] = G2_Y1;
        input[11] = G2_Y2;

        // Call pairing precompile
        uint256[1] memory result;
        bool success;

        assembly {
            success := staticcall(gas(), 0x08, input, 384, result, 32)
        }

        return success && result[0] == 1;
    }

    // ============================================================
    // Elliptic Curve Operations (using precompiles)
    // ============================================================

    /**
     * @notice EC point addition using EIP-196 precompile
     */
    function _ecAdd(
        uint256[2] memory p1,
        uint256[2] memory p2
    ) internal view returns (uint256[2] memory result) {
        uint256[4] memory input;
        input[0] = p1[0];
        input[1] = p1[1];
        input[2] = p2[0];
        input[3] = p2[1];

        bool success;
        assembly {
            success := staticcall(gas(), 0x06, input, 128, result, 64)
        }
        require(success, "EC add failed");
    }

    /**
     * @notice EC scalar multiplication using EIP-196 precompile
     */
    function _ecMul(
        uint256[2] memory p,
        uint256 s
    ) internal view returns (uint256[2] memory result) {
        uint256[3] memory input;
        input[0] = p[0];
        input[1] = p[1];
        input[2] = s;

        bool success;
        assembly {
            success := staticcall(gas(), 0x07, input, 96, result, 64)
        }
        require(success, "EC mul failed");
    }

    /**
     * @notice EC point negation
     */
    function _ecNeg(uint256[2] memory p) internal pure returns (uint256[2] memory) {
        if (p[0] == 0 && p[1] == 0) {
            return p;
        }
        return [p[0], FIELD_MODULUS - p[1]];
    }

    // ============================================================
    // Modular Arithmetic
    // ============================================================

    /**
     * @notice Modular exponentiation
     */
    function _expMod(
        uint256 base,
        uint256 exp,
        uint256 mod
    ) internal pure returns (uint256 result) {
        result = 1;
        base = base % mod;

        while (exp > 0) {
            if (exp % 2 == 1) {
                result = mulmod(result, base, mod);
            }
            exp = exp / 2;
            base = mulmod(base, base, mod);
        }
    }

    /**
     * @notice Modular multiplicative inverse using Fermat's little theorem
     */
    function _modInverse(uint256 a) internal pure returns (uint256) {
        return _expMod(a, SCALAR_MODULUS - 2, SCALAR_MODULUS);
    }
}
